<?php

use App\Http\Controllers\AdminAuthController;
use App\Http\Controllers\AdminMemberController;
use App\Http\Controllers\AdminSessionController;
use App\Http\Controllers\AdminTaskController;
use App\Http\Controllers\AnalyticsController;
use App\Http\Controllers\AttachmentController;
use App\Http\Controllers\HealthController;
use App\Http\Controllers\MaxWebhookController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\TaskFeaturesController;
use App\Http\Controllers\TaskWorkflowController;
use App\Http\Controllers\WorkerTaskController;
use Illuminate\Support\Facades\Route;

Route::get('/health/live', [HealthController::class, 'live']);
Route::get('/health/ready', [HealthController::class, 'ready']);
Route::post('/integrations/max/webhook', MaxWebhookController::class);
Route::get('/api/v1/auth/session', [AdminSessionController::class, 'show']);
Route::post('/api/v1/auth/login', [AdminAuthController::class, 'login']);
Route::post('/api/v1/auth/logout', [AdminAuthController::class, 'logout']);
Route::post('/api/v1/auth/password', [AdminAuthController::class, 'changePassword']);
Route::get('/api/v1/admin/members', [AdminMemberController::class, 'index']);
Route::get('/api/v1/admin/executors', [TaskFeaturesController::class, 'executors']);
Route::post('/api/v1/admin/members', [AdminMemberController::class, 'store']);
Route::put('/api/v1/admin/members/{id}/role', [AdminMemberController::class, 'changeRole']);
Route::get('/api/v1/admin/tasks', [AdminTaskController::class, 'index']);
Route::post('/api/v1/admin/tasks', [AdminTaskController::class, 'store']);
Route::post('/api/v1/admin/tasks/{id}/publish', [AdminTaskController::class, 'publish']);
Route::get('/api/v1/admin/tasks/{id}/applications', [TaskWorkflowController::class, 'applications']);
Route::post('/api/v1/admin/tasks/{id}/applications/{application}/decision', [TaskWorkflowController::class, 'decide']);
Route::post('/api/v1/admin/tasks/{id}/status', [TaskWorkflowController::class, 'adminStatus']);
Route::get('/api/v1/admin/fields', [TaskFeaturesController::class, 'fields']);
Route::post('/api/v1/admin/fields', [TaskFeaturesController::class, 'saveField']);
Route::get('/api/v1/admin/tasks/{id}/events', [TaskFeaturesController::class, 'events']);
Route::get('/api/v1/admin/tasks/{id}/rating', [TaskFeaturesController::class, 'getRating']);
Route::put('/api/v1/admin/tasks/{id}/rating', [TaskFeaturesController::class, 'putRating']);
Route::get('/api/v1/admin/applications', [TaskFeaturesController::class, 'allApplications']);
Route::get('/api/v1/admin/analytics', [AnalyticsController::class, 'index']);
Route::get('/api/v1/admin/analytics/trend', [AnalyticsController::class, 'trend']);
Route::get('/api/v1/admin/analytics.csv', [AnalyticsController::class, 'csv']);
Route::post('/api/v1/admin/tasks/{id}/attachments', [AttachmentController::class, 'upload']);
Route::get('/api/v1/admin/tasks/{id}/attachments', [AttachmentController::class, 'list']);
Route::get('/api/v1/worker/tasks/{id}/attachments', [AttachmentController::class, 'list']);
Route::get('/api/v1/worker/orders/{id}/attachments', [AttachmentController::class, 'list']);
Route::get('/api/v1/attachments/{id}', [AttachmentController::class, 'download']);
Route::post('/api/v1/worker/tasks/{id}/applications', [WorkerTaskController::class, 'apply']);
Route::get('/api/v1/worker/tasks', [WorkerTaskController::class, 'index']);
Route::get('/api/v1/worker/orders', [TaskWorkflowController::class, 'orders']);
Route::post('/api/v1/worker/orders/{id}/status', [TaskWorkflowController::class, 'orderStatus']);
Route::get('/api/v1/worker/notifications', [TaskWorkflowController::class, 'notifications']);
Route::get('/api/v1/worker/reputation', [TaskFeaturesController::class, 'reputation']);
Route::get('/api/v1/me/profile', [ProfileController::class, 'show']);
Route::put('/api/v1/me/profile', [ProfileController::class, 'update']);
