CREATE TABLE IF NOT EXISTS schema_migrations (
    version TEXT PRIMARY KEY,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS max_webhook_inbox (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    event_hash TEXT NOT NULL UNIQUE,
    payload JSONB NOT NULL,
    received_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
